version: "3"
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - 9000:9000
    volumes:
      - /opt/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - URL=rueberg.eu
      - VALIDATION=http
    volumes:
      - /opt/swag:/config
      - ~/.install/nginx:/config/nginx/custom
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
