# version: '3.2'
services:
  agent:
    image: appwrite/appwrite:1.2.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/appwrite:/usr/src/code/appwrite:rw
    ports:
      - "2222:22"
      - "80:80"
      - "443:443"
