name: 'Trigger Server Deploy Hook'
on:
  push:
    branches:
      - 'main'
jobs:
  run-server-hook:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Server Deploy Hook
      run: |
        curl -X GET "http://rueberg.eu:4005/hook-deploy"
